name: Jekyll site CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # or the version you're using
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Print installed gems
        run: bundle list      
      - name: Build the site
        run: bundle exec jekyll build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
      - name: set custom domain
        run: echo 'arba.pro' > ./build/CNAME && gh-pages -d build"
